/**
 * Generated by "@vuepress/internal-routes"
 */

import { injectComponentOption, ensureAsyncComponentsLoaded } from '@app/util'
import rootMixins from '@internal/root-mixins'
import GlobalLayout from "/Users/snopzyz/Documents/GitHub/test/node_modules/@vuepress/core/lib/client/components/GlobalLayout.vue"

injectComponentOption(GlobalLayout, 'mixins', rootMixins)
export const routes = [
  {
    name: "v-1fc22f70",
    path: "/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-1fc22f70").then(next)
    },
  },
  {
    path: "/index.html",
    redirect: "/"
  },
  {
    name: "v-eb61328e",
    path: "/blogs/algorithm/data-structure/cdq.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("article", "v-eb61328e").then(next)
    },
  },
  {
    name: "v-a4e952aa",
    path: "/blogs/algorithm/data-structure/divid-tree.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-a4e952aa").then(next)
    },
  },
  {
    name: "v-ce6b19aa",
    path: "/blogs/algorithm/data-structure/captain-mo.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("article", "v-ce6b19aa").then(next)
    },
  },
  {
    name: "v-788248ac",
    path: "/blogs/algorithm/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-788248ac").then(next)
    },
  },
  {
    path: "/blogs/algorithm/index.html",
    redirect: "/blogs/algorithm/"
  },
  {
    name: "v-f8b025ea",
    path: "/blogs/algorithm/data-structure/hash.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("article", "v-f8b025ea").then(next)
    },
  },
  {
    name: "v-5708d2cb",
    path: "/blogs/algorithm/data-structure/function-segmenttree.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("article", "v-5708d2cb").then(next)
    },
  },
  {
    name: "v-5954e312",
    path: "/blogs/algorithm/data-structure/segmenttree.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("article", "v-5954e312").then(next)
    },
  },
  {
    name: "v-5f1c9caa",
    path: "/blogs/algorithm/data-structure/unionset.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("article", "v-5f1c9caa").then(next)
    },
  },
  {
    name: "v-2a2c10aa",
    path: "/blogs/algorithm/dpp/line-DP.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("article", "v-2a2c10aa").then(next)
    },
  },
  {
    name: "v-1f3d212b",
    path: "/blogs/algorithm/dpp/backpack-DP.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("article", "v-1f3d212b").then(next)
    },
  },
  {
    name: "v-76c0de6a",
    path: "/blogs/algorithm/dpp/number-DP.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("article", "v-76c0de6a").then(next)
    },
  },
  {
    name: "v-5dd637ae",
    path: "/blogs/algorithm/else/suspendedline.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("article", "v-5dd637ae").then(next)
    },
  },
  {
    name: "v-64401ecb",
    path: "/blogs/algorithm/data-structure/trietree.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("article", "v-64401ecb").then(next)
    },
  },
  {
    name: "v-743ee46a",
    path: "/blogs/algorithm/graph/matrix-tree.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("article", "v-743ee46a").then(next)
    },
  },
  {
    name: "v-71b416de",
    path: "/blogs/algorithm/graph/differential-constraints.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("article", "v-71b416de").then(next)
    },
  },
  {
    name: "v-6b1345ab",
    path: "/blogs/algorithm/graph/2-sat.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("article", "v-6b1345ab").then(next)
    },
  },
  {
    name: "v-600a1f6b",
    path: "/blogs/algorithm/graph/kruskal.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("article", "v-600a1f6b").then(next)
    },
  },
  {
    name: "v-3264d90b",
    path: "/blogs/algorithm/graph/krusalnewtree.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-3264d90b").then(next)
    },
  },
  {
    name: "v-caaf06ce",
    path: "/blogs/algorithm/graph/prufer.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("article", "v-caaf06ce").then(next)
    },
  },
  {
    name: "v-4f326baa",
    path: "/blogs/algorithm/graph/tree-partitioning.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("article", "v-4f326baa").then(next)
    },
  },
  {
    name: "v-04f338ab",
    path: "/blogs/algorithm/math/ballandbox.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-04f338ab").then(next)
    },
  },
  {
    name: "v-74f67eab",
    path: "/blogs/algorithm/graph/minpath.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("article", "v-74f67eab").then(next)
    },
  },
  {
    name: "v-3f4660ce",
    path: "/blogs/algorithm/graph/virtual-tree.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("article", "v-3f4660ce").then(next)
    },
  },
  {
    name: "v-6f3c5242",
    path: "/blogs/algorithm/math/crt.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("article", "v-6f3c5242").then(next)
    },
  },
  {
    name: "v-2a9290eb",
    path: "/blogs/algorithm/math/bsgs.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("article", "v-2a9290eb").then(next)
    },
  },
  {
    name: "v-ed62c09e",
    path: "/blogs/algorithm/math/dirichlet-product.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("article", "v-ed62c09e").then(next)
    },
  },
  {
    name: "v-0b36d1cb",
    path: "/blogs/algorithm/math/euler-inversion.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("article", "v-0b36d1cb").then(next)
    },
  },
  {
    name: "v-c9f0fe82",
    path: "/blogs/algorithm/math/exgcd.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("article", "v-c9f0fe82").then(next)
    },
  },
  {
    name: "v-439d04b3",
    path: "/blogs/algorithm/math/gauss.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("article", "v-439d04b3").then(next)
    },
  },
  {
    name: "v-75af48d7",
    path: "/blogs/algorithm/math/euler.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("article", "v-75af48d7").then(next)
    },
  },
  {
    name: "v-0fcf4281",
    path: "/blogs/algorithm/math/fft.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("article", "v-0fcf4281").then(next)
    },
  },
  {
    name: "v-668222c9",
    path: "/blogs/algorithm/math/generate-function.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("article", "v-668222c9").then(next)
    },
  },
  {
    name: "v-6b54f0eb",
    path: "/blogs/algorithm/math/kangtuo.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("article", "v-6b54f0eb").then(next)
    },
  },
  {
    name: "v-72a17f2b",
    path: "/blogs/algorithm/math/gaming.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("article", "v-72a17f2b").then(next)
    },
  },
  {
    name: "v-4b66926b",
    path: "/blogs/algorithm/math/matrix-ksm.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("article", "v-4b66926b").then(next)
    },
  },
  {
    name: "v-6a522eeb",
    path: "/blogs/algorithm/math/mobius-inversion.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("article", "v-6a522eeb").then(next)
    },
  },
  {
    name: "v-47eb48ea",
    path: "/blogs/algorithm/math/lagrange-interpolation.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("article", "v-47eb48ea").then(next)
    },
  },
  {
    name: "v-7e8a3a26",
    path: "/blogs/algorithm/math/original-root.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("article", "v-7e8a3a26").then(next)
    },
  },
  {
    name: "v-94731aea",
    path: "/blogs/algorithm/search/bfs.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("article", "v-94731aea").then(next)
    },
  },
  {
    name: "v-45077021",
    path: "/blogs/algorithm/math/proof.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("article", "v-45077021").then(next)
    },
  },
  {
    name: "v-8ff80d0a",
    path: "/blogs/algorithm/string/kmp.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("article", "v-8ff80d0a").then(next)
    },
  },
  {
    name: "v-482e0587",
    path: "/blogs/algorithm/search/dfs.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("article", "v-482e0587").then(next)
    },
  },
  {
    name: "v-a43bf9d6",
    path: "/blogs/algorithm/math/line-base.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("article", "v-a43bf9d6").then(next)
    },
  },
  {
    name: "v-851b1736",
    path: "/blogs/book/agthm-bty/agthm-bty-pre.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-851b1736").then(next)
    },
  },
  {
    name: "v-55bfe1cb",
    path: "/blogs/algorithm/string/manacher.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("article", "v-55bfe1cb").then(next)
    },
  },
  {
    name: "v-6b1e84de",
    path: "/blogs/book/agthm-bty/agthm-bty.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-6b1e84de").then(next)
    },
  },
  {
    name: "v-ece72f84",
    path: "/blogs/configure/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-ece72f84").then(next)
    },
  },
  {
    path: "/blogs/configure/index.html",
    redirect: "/blogs/configure/"
  },
  {
    name: "v-7ed9b533",
    path: "/blogs/configure/macos/allcanhead.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-7ed9b533").then(next)
    },
  },
  {
    name: "v-7a2d18ee",
    path: "/blogs/solution/base/binary.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-7a2d18ee").then(next)
    },
  },
  {
    name: "v-48109900",
    path: "/blogs/book/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-48109900").then(next)
    },
  },
  {
    path: "/blogs/book/index.html",
    redirect: "/blogs/book/"
  },
  {
    name: "v-55e3bafa",
    path: "/blogs/solution/base/bruceforce.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-55e3bafa").then(next)
    },
  },
  {
    name: "v-0d88955e",
    path: "/blogs/solution/base/doas.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-0d88955e").then(next)
    },
  },
  {
    name: "v-5ff2be2a",
    path: "/blogs/solution/base/greedy-conclusion.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-5ff2be2a").then(next)
    },
  },
  {
    name: "v-6696e2cf",
    path: "/blogs/solution/base/sort.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-6696e2cf").then(next)
    },
  },
  {
    name: "v-c37676ea",
    path: "/blogs/solution/base/two-point.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-c37676ea").then(next)
    },
  },
  {
    name: "v-56af92cd",
    path: "/blogs/solution/base/conclusion.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-56af92cd").then(next)
    },
  },
  {
    name: "v-7f5d918b",
    path: "/blogs/solution/datastructure/bitset.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-7f5d918b").then(next)
    },
  },
  {
    name: "v-5d3c030e",
    path: "/blogs/solution/datastructure/block.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-5d3c030e").then(next)
    },
  },
  {
    name: "v-20c2fe6a",
    path: "/blogs/solution/base/sum-dir.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-20c2fe6a").then(next)
    },
  },
  {
    name: "v-5aa3f92b",
    path: "/blogs/solution/datastructure/hash.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-5aa3f92b").then(next)
    },
  },
  {
    name: "v-391b0719",
    path: "/blogs/solution/datastructure/monotonically-stack.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-391b0719").then(next)
    },
  },
  {
    name: "v-7cd6930b",
    path: "/blogs/solution/datastructure/chairmantree.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-7cd6930b").then(next)
    },
  },
  {
    name: "v-eafd451e",
    path: "/blogs/solution/datastructure/queue.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-eafd451e").then(next)
    },
  },
  {
    name: "v-e6d1649e",
    path: "/blogs/solution/datastructure/segmenttree.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-e6d1649e").then(next)
    },
  },
  {
    name: "v-efa5fe2a",
    path: "/blogs/solution/datastructure/priority-queue.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-efa5fe2a").then(next)
    },
  },
  {
    name: "v-5bd1b883",
    path: "/blogs/solution/datastructure/stack.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-5bd1b883").then(next)
    },
  },
  {
    name: "v-448960ea",
    path: "/blogs/solution/datastructure/st.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-448960ea").then(next)
    },
  },
  {
    name: "v-91c853c6",
    path: "/blogs/solution/datastructure/treearray.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-91c853c6").then(next)
    },
  },
  {
    name: "v-72111caa",
    path: "/blogs/solution/datastructure/trie.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-72111caa").then(next)
    },
  },
  {
    name: "v-481746ea",
    path: "/blogs/solution/datastructure/unionset.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-481746ea").then(next)
    },
  },
  {
    name: "v-862d637e",
    path: "/blogs/solution/dp/backpack.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-862d637e").then(next)
    },
  },
  {
    name: "v-7a518916",
    path: "/blogs/solution/dp/lr.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-7a518916").then(next)
    },
  },
  {
    name: "v-5dc2fcc1",
    path: "/blogs/solution/dp/get-number.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-5dc2fcc1").then(next)
    },
  },
  {
    name: "v-a97c6c4e",
    path: "/blogs/solution/dp/line.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-a97c6c4e").then(next)
    },
  },
  {
    name: "v-74c830ab",
    path: "/blogs/solution/dp/statement.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-74c830ab").then(next)
    },
  },
  {
    name: "v-5610fa2a",
    path: "/blogs/solution/else/levitation-line.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-5610fa2a").then(next)
    },
  },
  {
    name: "v-08860785",
    path: "/blogs/solution/dp/tree.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-08860785").then(next)
    },
  },
  {
    name: "v-2815fd09",
    path: "/blogs/solution/graph/connectcomponents.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-2815fd09").then(next)
    },
  },
  {
    name: "v-733ceeaf",
    path: "/blogs/solution/dp/number.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-733ceeaf").then(next)
    },
  },
  {
    name: "v-627c39f5",
    path: "/blogs/solution/graph/matrix-tree.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-627c39f5").then(next)
    },
  },
  {
    name: "v-5d73f769",
    path: "/blogs/solution/geometry/geometry.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-5d73f769").then(next)
    },
  },
  {
    name: "v-55bbfa19",
    path: "/blogs/solution/graph/differconnect.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-55bbfa19").then(next)
    },
  },
  {
    name: "v-6a89c8cb",
    path: "/blogs/solution/graph/minimum-spaning-tree.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-6a89c8cb").then(next)
    },
  },
  {
    name: "v-a396596a",
    path: "/blogs/solution/graph/prufer.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-a396596a").then(next)
    },
  },
  {
    name: "v-899f2d0e",
    path: "/blogs/solution/graph/partitiontree.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-899f2d0e").then(next)
    },
  },
  {
    name: "v-6ca6aa5e",
    path: "/blogs/solution/graph/starGraph.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-6ca6aa5e").then(next)
    },
  },
  {
    name: "v-f0e9a8aa",
    path: "/blogs/solution/graph/shortestpath.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-f0e9a8aa").then(next)
    },
  },
  {
    name: "v-1a70d007",
    path: "/blogs/solution/graph/treeproblem.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-1a70d007").then(next)
    },
  },
  {
    name: "v-fa0c0fba",
    path: "/blogs/solution/graph/topsort.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-fa0c0fba").then(next)
    },
  },
  {
    name: "v-4874424b",
    path: "/blogs/solution/graph/twograph.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-4874424b").then(next)
    },
  },
  {
    name: "v-0c4f08c8",
    path: "/blogs/solution/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-0c4f08c8").then(next)
    },
  },
  {
    path: "/blogs/solution/index.html",
    redirect: "/blogs/solution/"
  },
  {
    name: "v-5045d466",
    path: "/blogs/solution/math/combine-math.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-5045d466").then(next)
    },
  },
  {
    name: "v-2b4cf22a",
    path: "/blogs/solution/math/crt.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-2b4cf22a").then(next)
    },
  },
  {
    name: "v-0d8af98b",
    path: "/blogs/solution/math/congruence-equation.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-0d8af98b").then(next)
    },
  },
  {
    name: "v-9c5d72b6",
    path: "/blogs/solution/math/highmath.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-9c5d72b6").then(next)
    },
  },
  {
    name: "v-c2b474ea",
    path: "/blogs/solution/math/exact-divid.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-c2b474ea").then(next)
    },
  },
  {
    name: "v-42efab95",
    path: "/blogs/solution/math/game.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-42efab95").then(next)
    },
  },
  {
    name: "v-411a6a4b",
    path: "/blogs/solution/math/replace-group.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-411a6a4b").then(next)
    },
  },
  {
    name: "v-0123e74b",
    path: "/blogs/solution/offline/captain-mo.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-0123e74b").then(next)
    },
  },
  {
    name: "v-68325791",
    path: "/blogs/solution/math/polynomial.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-68325791").then(next)
    },
  },
  {
    name: "v-426cfc8e",
    path: "/blogs/solution/math/linear-algebra.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-426cfc8e").then(next)
    },
  },
  {
    name: "v-1e48f3aa",
    path: "/blogs/solution/math/euler-inversion.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-1e48f3aa").then(next)
    },
  },
  {
    name: "v-71e9776a",
    path: "/blogs/solution/math/sieve.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-71e9776a").then(next)
    },
  },
  {
    name: "v-b1c51b3a",
    path: "/blogs/solution/offline/preferorder.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-b1c51b3a").then(next)
    },
  },
  {
    name: "v-50957eab",
    path: "/blogs/solution/search/BFS.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-50957eab").then(next)
    },
  },
  {
    name: "v-3df671ab",
    path: "/blogs/solution/string/KMP.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-3df671ab").then(next)
    },
  },
  {
    name: "v-d2e30b6a",
    path: "/blogs/solution/search/permutation.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-d2e30b6a").then(next)
    },
  },
  {
    name: "v-6bbc2e4b",
    path: "/dairy.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-6bbc2e4b").then(next)
    },
  },
  {
    name: "v-5630a72a",
    path: "/docs/theme-reco/api.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-5630a72a").then(next)
    },
  },
  {
    name: "v-47a77f6b",
    path: "/blogs/solution/search/DFS.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-47a77f6b").then(next)
    },
  },
  {
    name: "v-d1f4997e",
    path: "/docs/theme-reco/plugin.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-d1f4997e").then(next)
    },
  },
  {
    name: "v-7e125c19",
    path: "/blogs/solution/string/Manacher.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-7e125c19").then(next)
    },
  },
  {
    name: "v-1f297fc0",
    path: "/docs/theme-reco/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-1f297fc0").then(next)
    },
  },
  {
    path: "/docs/theme-reco/index.html",
    redirect: "/docs/theme-reco/"
  },
  {
    name: "v-598dbe8b",
    path: "/docs/theme-reco/theme.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-598dbe8b").then(next)
    },
  },
  {
    name: "v-033c129f",
    path: "/blogs/solution/math/mobius-inversion.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-033c129f").then(next)
    },
  },
  {
    name: "v-b90240aa",
    path: "/rewards.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-b90240aa").then(next)
    },
  },
  {
    name: "v-2a76442a",
    path: "/person-wechat.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-2a76442a").then(next)
    },
  },
  {
    name: "v-b1564aac",
    path: "/tag/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Tags", "v-b1564aac").then(next)
    },
    meta: {"pid":"tags","id":"tags"}
  },
  {
    path: "/tag/index.html",
    redirect: "/tag/"
  },
  {
    name: "v-ef9325c4",
    path: "/categories/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("FrontmatterKey", "v-ef9325c4").then(next)
    },
    meta: {"pid":"categories","id":"categories"}
  },
  {
    path: "/categories/index.html",
    redirect: "/categories/"
  },
  {
    name: "v-6319eb4e",
    path: "/timeline/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("TimeLines", "v-6319eb4e").then(next)
    },
    meta: {"pid":"timeline","id":"timeline"}
  },
  {
    path: "/timeline/index.html",
    redirect: "/timeline/"
  },
  {
    name: "v-19490cfb",
    path: "/tag/离线算法/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Tag", "v-19490cfb").then(next)
    },
    meta: {"pid":"tags","id":"离线算法"}
  },
  {
    path: "/tag/离线算法/index.html",
    redirect: "/tag/离线算法/"
  },
  {
    name: "v-92b3076c",
    path: "/tag/数据结构/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Tag", "v-92b3076c").then(next)
    },
    meta: {"pid":"tags","id":"数据结构"}
  },
  {
    path: "/tag/数据结构/index.html",
    redirect: "/tag/数据结构/"
  },
  {
    name: "v-e55a7dbe",
    path: "/tag/动态规划/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Tag", "v-e55a7dbe").then(next)
    },
    meta: {"pid":"tags","id":"动态规划"}
  },
  {
    path: "/tag/动态规划/index.html",
    redirect: "/tag/动态规划/"
  },
  {
    name: "v-43a4e3fe",
    path: "/tag/图论/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Tag", "v-43a4e3fe").then(next)
    },
    meta: {"pid":"tags","id":"图论"}
  },
  {
    path: "/tag/图论/index.html",
    redirect: "/tag/图论/"
  },
  {
    name: "v-6ddcedaa",
    path: "/tag/建图/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Tag", "v-6ddcedaa").then(next)
    },
    meta: {"pid":"tags","id":"建图"}
  },
  {
    path: "/tag/建图/index.html",
    redirect: "/tag/建图/"
  },
  {
    name: "v-d4b78318",
    path: "/tag/建图、Kosaraju/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Tag", "v-d4b78318").then(next)
    },
    meta: {"pid":"tags","id":"建图、Kosaraju"}
  },
  {
    path: "/tag/建图、Kosaraju/index.html",
    redirect: "/tag/建图、Kosaraju/"
  },
  {
    name: "v-73e170ba",
    path: "/tag/树/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Tag", "v-73e170ba").then(next)
    },
    meta: {"pid":"tags","id":"树"}
  },
  {
    path: "/tag/树/index.html",
    redirect: "/tag/树/"
  },
  {
    name: "v-7fd1851a",
    path: "/tag/数论/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Tag", "v-7fd1851a").then(next)
    },
    meta: {"pid":"tags","id":"数论"}
  },
  {
    path: "/tag/数论/index.html",
    redirect: "/tag/数论/"
  },
  {
    name: "v-481fe1e6",
    path: "/tag/数学/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Tag", "v-481fe1e6").then(next)
    },
    meta: {"pid":"tags","id":"数学"}
  },
  {
    path: "/tag/数学/index.html",
    redirect: "/tag/数学/"
  },
  {
    name: "v-771b1f98",
    path: "/tag/搜索/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Tag", "v-771b1f98").then(next)
    },
    meta: {"pid":"tags","id":"搜索"}
  },
  {
    path: "/tag/搜索/index.html",
    redirect: "/tag/搜索/"
  },
  {
    name: "v-a89d92d8",
    path: "/tag/推导/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Tag", "v-a89d92d8").then(next)
    },
    meta: {"pid":"tags","id":"推导"}
  },
  {
    path: "/tag/推导/index.html",
    redirect: "/tag/推导/"
  },
  {
    name: "v-2bb7b0b6",
    path: "/tag/字符串/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Tag", "v-2bb7b0b6").then(next)
    },
    meta: {"pid":"tags","id":"字符串"}
  },
  {
    path: "/tag/字符串/index.html",
    redirect: "/tag/字符串/"
  },
  {
    name: "v-17c9b307",
    path: "/categories/离线算法/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Category", "v-17c9b307").then(next)
    },
    meta: {"pid":"categories","id":"离线算法"}
  },
  {
    path: "/categories/离线算法/index.html",
    redirect: "/categories/离线算法/"
  },
  {
    name: "v-95b1bb54",
    path: "/categories/数据结构/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Category", "v-95b1bb54").then(next)
    },
    meta: {"pid":"categories","id":"数据结构"}
  },
  {
    path: "/categories/数据结构/index.html",
    redirect: "/categories/数据结构/"
  },
  {
    name: "v-e85931a6",
    path: "/categories/动态规划/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Category", "v-e85931a6").then(next)
    },
    meta: {"pid":"categories","id":"动态规划"}
  },
  {
    path: "/categories/动态规划/index.html",
    redirect: "/categories/动态规划/"
  },
  {
    name: "v-ad7841e6",
    path: "/categories/图论/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Category", "v-ad7841e6").then(next)
    },
    meta: {"pid":"categories","id":"图论"}
  },
  {
    path: "/categories/图论/index.html",
    redirect: "/categories/图论/"
  },
  {
    name: "v-133632f2",
    path: "/categories/数学/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Category", "v-133632f2").then(next)
    },
    meta: {"pid":"categories","id":"数学"}
  },
  {
    path: "/categories/数学/index.html",
    redirect: "/categories/数学/"
  },
  {
    name: "v-423170a4",
    path: "/categories/搜索/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Category", "v-423170a4").then(next)
    },
    meta: {"pid":"categories","id":"搜索"}
  },
  {
    path: "/categories/搜索/index.html",
    redirect: "/categories/搜索/"
  },
  {
    name: "v-76c787a0",
    path: "/categories/推导/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Category", "v-76c787a0").then(next)
    },
    meta: {"pid":"categories","id":"推导"}
  },
  {
    path: "/categories/推导/index.html",
    redirect: "/categories/推导/"
  },
  {
    name: "v-2feb77ce",
    path: "/categories/字符串/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Category", "v-2feb77ce").then(next)
    },
    meta: {"pid":"categories","id":"字符串"}
  },
  {
    path: "/categories/字符串/index.html",
    redirect: "/categories/字符串/"
  },
  {
    name: "v-33d96517",
    path: "/tag/数学/page/2/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-33d96517").then(next)
    },
    meta: {"pid":"tags","id":"数学"}
  },
  {
    path: "/tag/数学/page/2/index.html",
    redirect: "/tag/数学/page/2/"
  },
  {
    name: "v-01c40e8b",
    path: "/categories/数学/page/2/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-01c40e8b").then(next)
    },
    meta: {"pid":"categories","id":"数学"}
  },
  {
    path: "/categories/数学/page/2/index.html",
    redirect: "/categories/数学/page/2/"
  },
  {
    path: '*',
    component: GlobalLayout
  }
]