/**
 * Generated by "@vuepress/plugin-blog"
 */
export default {
  "tags": {
    "离线算法": {
      "key": "离线算法",
      "scope": "tags",
      "path": "/tag/离线算法/",
      "pageKeys": [
        "v-eb61328e"
      ]
    },
    "数据结构": {
      "key": "数据结构",
      "scope": "tags",
      "path": "/tag/数据结构/",
      "pageKeys": [
        "v-f8b025ea",
        "v-5708d2cb",
        "v-ce6b19aa",
        "v-5f1c9caa",
        "v-5954e312",
        "v-64401ecb"
      ]
    },
    "动态规划": {
      "key": "动态规划",
      "scope": "tags",
      "path": "/tag/动态规划/",
      "pageKeys": [
        "v-2a2c10aa",
        "v-76c0de6a",
        "v-1f3d212b",
        "v-5dd637ae"
      ]
    },
    "建图、Kosaraju": {
      "key": "建图、Kosaraju",
      "scope": "tags",
      "path": "/tag/建图、Kosaraju/",
      "pageKeys": [
        "v-6b1345ab"
      ]
    },
    "图论": {
      "key": "图论",
      "scope": "tags",
      "path": "/tag/图论/",
      "pageKeys": [
        "v-743ee46a",
        "v-74f67eab",
        "v-caaf06ce",
        "v-3f4660ce",
        "v-600a1f6b"
      ]
    },
    "建图": {
      "key": "建图",
      "scope": "tags",
      "path": "/tag/建图/",
      "pageKeys": [
        "v-71b416de"
      ]
    },
    "数论": {
      "key": "数论",
      "scope": "tags",
      "path": "/tag/数论/",
      "pageKeys": [
        "v-6f3c5242",
        "v-75af48d7",
        "v-2a9290eb",
        "v-0fcf4281",
        "v-6a522eeb"
      ]
    },
    "数学": {
      "key": "数学",
      "scope": "tags",
      "path": "/tag/数学/",
      "pageKeys": [
        "v-ed62c09e",
        "v-0b36d1cb",
        "v-c9f0fe82",
        "v-72a17f2b",
        "v-439d04b3",
        "v-6b54f0eb",
        "v-47eb48ea",
        "v-668222c9",
        "v-a43bf9d6",
        "v-4b66926b",
        "v-7e8a3a26"
      ]
    },
    "树": {
      "key": "树",
      "scope": "tags",
      "path": "/tag/树/",
      "pageKeys": [
        "v-4f326baa"
      ]
    },
    "字符串": {
      "key": "字符串",
      "scope": "tags",
      "path": "/tag/字符串/",
      "pageKeys": [
        "v-8ff80d0a",
        "v-55bfe1cb"
      ]
    },
    "搜索": {
      "key": "搜索",
      "scope": "tags",
      "path": "/tag/搜索/",
      "pageKeys": [
        "v-482e0587",
        "v-94731aea"
      ]
    },
    "推导": {
      "key": "推导",
      "scope": "tags",
      "path": "/tag/推导/",
      "pageKeys": [
        "v-45077021"
      ]
    }
  },
  "categories": {
    "离线算法": {
      "key": "离线算法",
      "scope": "categories",
      "path": "/categories/离线算法/",
      "pageKeys": [
        "v-eb61328e"
      ]
    },
    "数据结构": {
      "key": "数据结构",
      "scope": "categories",
      "path": "/categories/数据结构/",
      "pageKeys": [
        "v-f8b025ea",
        "v-5708d2cb",
        "v-ce6b19aa",
        "v-5f1c9caa",
        "v-5954e312",
        "v-64401ecb"
      ]
    },
    "动态规划": {
      "key": "动态规划",
      "scope": "categories",
      "path": "/categories/动态规划/",
      "pageKeys": [
        "v-2a2c10aa",
        "v-76c0de6a",
        "v-1f3d212b",
        "v-5dd637ae"
      ]
    },
    "图论": {
      "key": "图论",
      "scope": "categories",
      "path": "/categories/图论/",
      "pageKeys": [
        "v-6b1345ab",
        "v-743ee46a",
        "v-74f67eab",
        "v-caaf06ce",
        "v-71b416de",
        "v-3f4660ce",
        "v-600a1f6b",
        "v-4f326baa"
      ]
    },
    "数学": {
      "key": "数学",
      "scope": "categories",
      "path": "/categories/数学/",
      "pageKeys": [
        "v-6f3c5242",
        "v-ed62c09e",
        "v-0b36d1cb",
        "v-75af48d7",
        "v-c9f0fe82",
        "v-2a9290eb",
        "v-72a17f2b",
        "v-439d04b3",
        "v-0fcf4281",
        "v-6b54f0eb",
        "v-47eb48ea",
        "v-668222c9",
        "v-a43bf9d6",
        "v-6a522eeb",
        "v-4b66926b",
        "v-7e8a3a26"
      ]
    },
    "字符串": {
      "key": "字符串",
      "scope": "categories",
      "path": "/categories/字符串/",
      "pageKeys": [
        "v-8ff80d0a",
        "v-55bfe1cb"
      ]
    },
    "搜索": {
      "key": "搜索",
      "scope": "categories",
      "path": "/categories/搜索/",
      "pageKeys": [
        "v-482e0587",
        "v-94731aea"
      ]
    },
    "推导": {
      "key": "推导",
      "scope": "categories",
      "path": "/categories/推导/",
      "pageKeys": [
        "v-45077021"
      ]
    }
  },
  "timeline": {}
}